[2024-01-29T03:21:33.838+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_exec_scripts_demo.clnuptable_task manual__2024-01-28T21:51:26.396881+00:00 [queued]>
[2024-01-29T03:21:33.849+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_exec_scripts_demo.clnuptable_task manual__2024-01-28T21:51:26.396881+00:00 [queued]>
[2024-01-29T03:21:33.850+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-29T03:21:33.885+0530] {taskinstance.py:2191} INFO - Executing <Task(MySqlOperator): clnuptable_task> on 2024-01-28 21:51:26.396881+00:00
[2024-01-29T03:21:33.891+0530] {standard_task_runner.py:60} INFO - Started process 12106 to run task
[2024-01-29T03:21:33.899+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'dag_exec_scripts_demo', 'clnuptable_task', 'manual__2024-01-28T21:51:26.396881+00:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/6-create-dag-execute-scripts.py', '--cfg-path', '/tmp/tmp1r6dgval']
[2024-01-29T03:21:33.901+0530] {standard_task_runner.py:88} INFO - Job 340: Subtask clnuptable_task
[2024-01-29T03:21:33.947+0530] {task_command.py:423} INFO - Running <TaskInstance: dag_exec_scripts_demo.clnuptable_task manual__2024-01-28T21:51:26.396881+00:00 [running]> on host mh1.myguest.virtualbox.org
[2024-01-29T03:21:34.020+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_exec_scripts_demo' AIRFLOW_CTX_TASK_ID='clnuptable_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-28T21:51:26.396881+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-28T21:51:26.396881+00:00'
[2024-01-29T03:21:34.021+0530] {sql.py:276} INFO - Executing: delete from airflownew.employees
[2024-01-29T03:21:34.028+0530] {base.py:83} INFO - Using connection ID 'airflow_db' for task execution.
[2024-01-29T03:21:34.060+0530] {base.py:83} INFO - Using connection ID 'airflow_db' for task execution.
[2024-01-29T03:21:34.071+0530] {sql.py:450} INFO - Running statement: delete from airflownew.employees, parameters: None
[2024-01-29T03:21:34.073+0530] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hdu/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/hdu/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/hdu/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/hdu/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1049, "Unknown database 'airflownew'")
[2024-01-29T03:21:34.079+0530] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_exec_scripts_demo, task_id=clnuptable_task, execution_date=20240128T215126, start_date=20240128T215133, end_date=20240128T215134
[2024-01-29T03:21:34.103+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 340 for task clnuptable_task ((1049, "Unknown database 'airflownew'"); 12106)
[2024-01-29T03:21:34.150+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-29T03:21:34.180+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
